SET DEFINE OFF;
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (7, 'Telenor ', 'Srbija', 0, 
    '100', 11000, '66666666');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (8, 'Izi', 'Bosna', 0, 
    '100', 11000, '777777');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (1, 'mt:s', 'Takovska 2', 70203, 
    '100', 11000, '100002887');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (2, 'Vip Mobile', 'Omladinskih brigada 21', 70181, 
    '100', 11070, '104704549');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (3, 'MTEL', 'BOSNA', 0, 
    '100', 11000, '9999999');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (4, 'BH', 'BOSNA', 0, 
    '100', 11000, '8888888');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (5, 'HALOO', 'BOSNA', 0, 
    '100', 11000, '7777777');
Insert into EVD.CIS_SERVICE_PROVIDERS
   (SERVICE_PROVIDER_ID, SERVICE_PROVIDER_NAME, SERVICE_PROVIDER_ADDRESS, DISTRICT_ID, SERVICE_PROVIDER_STATUS, ZIP_CODE_ID, SERVICE_PROVIDER_PIB)
 Values
   (6, 'ERONET', 'BOSNA', 0, 
    '100', 11000, '66666666');
COMMIT;
