SET DEFINE OFF;
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_SETUP_DATE, DISTRIBUTOR_STATUS)
 Values
   (51, 'Octopus doo', 'Banja Luka', TO_DATE('02/13/2013 12:46:27', 'MM/DD/YYYY HH24:MI:SS'), '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_SETUP_DATE, DISTRIBUTOR_STATUS)
 Values
   (122, 'Autoritas ', 'Novi Sad', TO_DATE('03/04/2013 21:52:19', 'MM/DD/YYYY HH24:MI:SS'), '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_SETUP_DATE, DISTRIBUTOR_STATUS)
 Values
   (71, 'NIS a.d.', 'Novi Sad', TO_DATE('03/13/2013 23:16:31', 'MM/DD/YYYY HH24:MI:SS'), '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (1, 'DTM INVESTMENTS', 'Beograd', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_SETUP_DATE, DISTRIBUTOR_STATUS)
 Values
   (41, 'DTM doo Banja Luka', 'Banja Luka', TO_DATE('06/30/2011 19:40:09', 'MM/DD/YYYY HH24:MI:SS'), '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (81, 'Dilton d.o.o.', 'Beograd', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (85, 'Promtel d.o.o', 'Arandjelovac', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (101, 'MetohCo d.o.o', 'Beograd', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (121, 'Veletabak d.o.o', 'Novi Sad', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (82, 'Alego Company d.o.o.', 'Beograd', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (72, 'Telering', 'Banja Luka', '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_SETUP_DATE, DISTRIBUTOR_STATUS)
 Values
   (61, 'MBA Miljkovic d.o.o.', 'Beograd', TO_DATE('05/04/2012 16:25:44', 'MM/DD/YYYY HH24:MI:SS'), '100');
Insert into EVD.CIS_DISTRIBUTORS
   (DISTRIBUTOR_ID, DISTRIBUTOR_NAME, DISTRIBUTOR_ADDRESS, DISTRIBUTOR_STATUS)
 Values
   (83, 'P.T.I. d.o.o.', 'Beograd', '100');
COMMIT;
