SET DEFINE OFF;
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (9, 'TOP', 'Topup request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (10, 'REV', 'Reversal request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (12, 'RVR', 'Reversal request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (11, 'DTX', 'Topup request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (3, 'STO', 'Reversal request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (6, 'IZV', 'Reports');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (7, 'FIR', 'Firmware request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (8, 'FFF', 'Firmware download');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (1, 'DAT', 'Synhronization message');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (2, 'DOP', 'Topup request');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (4, 'STA', 'Status check');
Insert into EVD.COS_TRANSACTION_TYPES
   (TRANSACTION_TYPE_ID, TRANSACTION_TYPE, TRANSACTION_TYPE_DESCRIPTION)
 Values
   (5, 'LAS', 'Last transaction');
COMMIT;
